# Generated by Django 6.1.1 on 2026-09-07 11:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('outlook', models.TextField(blank=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CareerSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('importance', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_requirements', to='skills.skill')),
            ],
            options={
                'ordering': ['-importance', '-target_level', 'skill__name'],
                'constraints': [models.UniqueConstraint(fields=('career', 'skill'), name='unique_career_skill_requirement')],
            },
        ),
    ]
