# Generated by Django 6.1.1 on 2026-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='domain_keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='career',
            name='learning_areas',
            field=models.TextField(blank=True),
        ),
    ]
