# Generated by Django 6.1.1 on 2026-09-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_career_domain_keywords_career_learning_areas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careerskillrequirement',
            options={'ordering': ['-target_level', 'skill__name']},
        ),
    ]
