# Generated by Django 6.1.1 on 2026-09-09 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('REJECTED', 'Rejected'), ('SELECTED', 'Selected')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='applications.application')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='career_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.DecimalField(decimal_places=1, max_digits=5)),
                ('required_level', models.PositiveSmallIntegerField()),
                ('gap_percentage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gap_class', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('recommended_action', models.TextField(blank=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='feedback.applicationfeedback')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_gaps', to='skills.skill')),
            ],
            options={
                'ordering': ['-gap_percentage', 'skill__name'],
                'constraints': [models.UniqueConstraint(fields=('feedback', 'skill'), name='unique_feedback_skill_gap')],
            },
        ),
    ]
